export const DATA_ENTITIES = {
  DATA: 'data',
};

export const GET_UTILITY_DATA_START = 'GET_UTILITY_DATA_START';
export const GET_UTILITY_DATA_SUCCESS = 'GET_UTILITY_DATA_SUCCESS';
export const GET_UTILITY_DATA_FAIL = 'GET_UTILITY_DATA_FAIL';
export const CLEAR_UTILITY_DATA = 'CLEAR_UTILITY_DATA';

export const LOAD_MORE_UTILITY_ITEMS_REQUEST = 'LOAD_MORE_UTILITY_ITEMS_REQUEST';
export const LOAD_MORE_UTILITY_ITEMS_START = 'LOAD_MORE_UTILITY_ITEMS_START';
export const LOAD_MORE_UTILITY_ITEMS_SUCCESS = 'LOAD_MORE_UTILITY_ITEMS_SUCCESS';
export const LOAD_MORE_UTILITY_ITEMS_FAIL = 'LOAD_MORE_UTILITY_ITEMS_FAIL';
